name: PHP Lint check
on: [push, pull_request]
jobs:
  lint:
    name: PHP Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: PHP syntax checker 7.4
        uses: StephaneBour/actions-php-lint@7.4
      - name: PHP syntax checker 7.3
        uses: StephaneBour/actions-php-lint@7.3
      - name: PHP syntax checker 7.2
        uses: StephaneBour/actions-php-lint@7.2
      - name: PHP syntax checker 7.1
        uses: StephaneBour/actions-php-lint@7.1
      - name: PHP syntax checker 7.0
        uses: StephaneBour/actions-php-lint@7.0
